const items = [
  {
    id: "1",
    item_image: "../pics/product_pic_1.webp",
    brand_name: "New Brand 1",
    item_name: "Stylish Floral Earrings",
    original_Price: 1200,
    current_price: 750,
    percentile_cutoff: 37,
    return_period: 30,
    delivery_date: "15 Nov 2023",
    rating: {
      stars: 4.8,
      reviews: 2100,
    },
  },
  {
    id: "2",
    item_image: "../pics/product_pic_2.webp",
    brand_name: "Swim Co",
    item_name: "Elegant One-Piece Swimsuit",
    original_Price: 3000,
    current_price: 1800,
    percentile_cutoff: 40,
    return_period: 14,
    delivery_date: "12 Nov 2023",
    rating: {
      stars: 4.5,
      reviews: 50,
    },
  },
  {
    id: "3",
    item_image: "../pics/product_pic_3.webp",
    brand_name: "Fashionista",
    item_name: "Chic A-Line Skirt",
    original_Price: 1800,
    current_price: 600,
    percentile_cutoff: 66,
    return_period: 20,
    delivery_date: "11 Nov 2023",
    rating: {
      stars: 4.3,
      reviews: 300,
    },
  },
  {
    id: "4",
    item_image: "../pics/product_pic_4.webp",
    brand_name: "SPORTSGEAR",
    item_name: "National Team Cricket Jersey",
    original_Price: 1500,
    current_price: 1200,
    percentile_cutoff: 20,
    return_period: 14,
    delivery_date: "10 Nov 2023",
    rating: {
      stars: 4.9,
      reviews: 150,
    },
  },
  {
    id: "5",
    item_image: "../pics/product_pic_5.webp",
    brand_name: "Casual Wear",
    item_name: "Comfort Cotton T-shirt",
    original_Price: 1500,
    current_price: 500,
    percentile_cutoff: 67,
    return_period: 14,
    delivery_date: "18 Nov 2023",
    rating: {
      stars: 4.4,
      reviews: 4000,
    },
  },
  {
    id: "6",
    item_image: "../pics/product_pic_6.webp",
    brand_name: "Runner Pro",
    item_name: "Advanced Running Shoes",
    original_Price: 16000,
    current_price: 15500,
    percentile_cutoff: 3,
    return_period: 14,
    delivery_date: "10 Nov 2023",
    rating: {
      stars: 4.0,
      reviews: 5,
    },
  },
  {
    id: "7",
    item_image: "../pics/product_pic_7.webp",
    brand_name: "Urban Style",
    item_name: "Men's Regular Fit Shorts",
    original_Price: 1700,
    current_price: 700,
    percentile_cutoff: 59,
    return_period: 14,
    delivery_date: "13 Nov 2023",
    rating: {
      stars: 4.1,
      reviews: 450,
    },
  },
  {
    id: "8",
    item_image: "../pics/product_pic_8.webp",
    brand_name: "Grooming Essentials",
    item_name: "Men's Deodrant Spray 200ml",
    original_Price: 300,
    current_price: 150,
    percentile_cutoff: 50,
    return_period: 14,
    delivery_date: "10 Nov 2023",
    rating: {
      stars: 4.3,
      reviews: 6000,
    },
  },
  {
    id: "9",
    item_image: "../pics/product_pic_9.webp",
    brand_name: "Sporty",
    item_name: "Men's Polo T-shirt",
    original_Price: 1400,
    current_price: 900,
    percentile_cutoff: 36,
    return_period: 14,
    delivery_date: "14 Nov 2023",
    rating: {
      stars: 4.5,
      reviews: 1500,
    },
  },
  {
    id: "10",
    item_image: "../pics/product_pic_10.webp",
    brand_name: "Denim Co",
    item_name: "Men's Slim Fit Jeans",
    original_Price: 2800,
    current_price: 1600,
    percentile_cutoff: 43,
    return_period: 14,
    delivery_date: "16 Nov 2023",
    rating: {
      stars: 4.2,
      reviews: 950,
    },
  },
  {
    id: "11",
    item_image: "../pics/product_pic_11.webp",
    brand_name: "TechWear",
    item_name: "Smart Fitness Watch",
    original_Price: 8500,
    current_price: 6800,
    percentile_cutoff: 20,
    return_period: 30,
    delivery_date: "17 Nov 2023",
    rating: {
      stars: 4.6,
      reviews: 1200,
    },
  },
  {
    id: "12",
    item_image: "../pics/product_pic_12.webp",
    brand_name: "Luxury Bags",
    item_name: "Premium Leather Handbag",
    original_Price: 12000,
    current_price: 9600,
    percentile_cutoff: 20,
    return_period: 30,
    delivery_date: "19 Nov 2023",
    rating: {
      stars: 4.7,
      reviews: 850,
    },
  },
  {
    id: "13",
    item_image: "../pics/product_pic_13.webp",
    brand_name: "Home Decor",
    item_name: "Decorative Table Lamp",
    original_Price: 3500,
    current_price: 2100,
    percentile_cutoff: 40,
    return_period: 14,
    delivery_date: "20 Nov 2023",
    rating: {
      stars: 4.3,
      reviews: 320,
    },
  },
  {
    id: "14",
    item_image: "../pics/product_pic_14.webp",
    brand_name: "Kitchen Pro",
    item_name: "Non-Stick Cookware Set",
    original_Price: 5500,
    current_price: 3850,
    percentile_cutoff: 30,
    return_period: 30,
    delivery_date: "18 Nov 2023",
    rating: {
      stars: 4.5,
      reviews: 2200,
    },
  },
  {
    id: "15",
    item_image: "../pics/product_pic_15.webp",
    brand_name: "BookWorm",
    item_name: "Classic Literature Collection",
    original_Price: 2500,
    current_price: 1750,
    percentile_cutoff: 30,
    return_period: 14,
    delivery_date: "22 Nov 2023",
    rating: {
      stars: 4.8,
      reviews: 450,
    },
  },
  {
    id: "16",
    item_image: "../pics/product_pic_16.webp",
    brand_name: "Audio Tech",
    item_name: "Wireless Bluetooth Headphones",
    original_Price: 4500,
    current_price: 3150,
    percentile_cutoff: 30,
    return_period: 30,
    delivery_date: "21 Nov 2023",
    rating: {
      stars: 4.4,
      reviews: 1800,
    },
  },
  {
    id: "17",
    item_image: "../pics/product_pic_17.webp",
    brand_name: "Garden Plus",
    item_name: "Indoor Plant Pot Set",
    original_Price: 1800,
    current_price: 1260,
    percentile_cutoff: 30,
    return_period: 14,
    delivery_date: "23 Nov 2023",
    rating: {
      stars: 4.2,
      reviews: 680,
    },
  },
  {
    id: "18",
    item_image: "../pics/product_pic_18.webp",
    brand_name: "Office Essentials",
    item_name: "Ergonomic Office Chair",
    original_Price: 15000,
    current_price: 12000,
    percentile_cutoff: 20,
    return_period: 30,
    delivery_date: "25 Nov 2023",
    rating: {
      stars: 4.6,
      reviews: 950,
    },
  },
  {
    id: "19",
    item_image: "../pics/product_pic_19.webp",
    brand_name: "Beauty Care",
    item_name: "Skincare Routine Kit",
    original_Price: 3200,
    current_price: 2240,
    percentile_cutoff: 30,
    return_period: 14,
    delivery_date: "24 Nov 2023",
    rating: {
      stars: 4.5,
      reviews: 1350,
    },
  },
  {
    id: "20",
    item_image: "../pics/product_pic_20.webp",
    brand_name: "Travel Gear",
    item_name: "Lightweight Travel Backpack",
    original_Price: 4200,
    current_price: 2940,
    percentile_cutoff: 30,
    return_period: 30,
    delivery_date: "26 Nov 2023",
    rating: {
      stars: 4.7,
      reviews: 720,
    },
  },
];